open keyword "D:\MXDigitalTwinModeller\Test\ASTM_E8_optimization\ASTM_E8.k"
 Time to read keyword file =  1.094 seconds
 Time to process element data =  0.562 seconds
Finished reading model
assembly hilight fem 1
clearid part
partdata readlist 20 
clearid part
Solid Part #20 
partdata readlist 20  22  23  24  25 
clearid part
Solid Part #20 
Solid Part #22 
Solid Part #23 
Solid Part #24 
Solid Part #25 
partdata readlist  20  22  23  24  25 
clearid part
Solid Part #20 
Solid Part #22 
Solid Part #23 
Solid Part #24 
Solid Part #25 
clearid part
partdata readlist 20 
clearid part
Solid Part #20 
partdata readlist 23 
clearid part
Solid Part #23 
partdata readlist 24 
clearid part
Solid Part #24 
partdata readlist 25 
clearid part
Solid Part #25 
Coincident nodes found. Select node ID
Nothing picked !
Nothing picked !
center 5.000011 6.250000 0.000000
displayentity Set Node off all
displayentity Set Node on 1
displayentity Set Node off all
displayentity Set Node off all
displayentity Set Node on 1
center -20.000006 6.250000 0.000000
displayentity Set Node off all
displayentity Set Node on 2
displayentity Set Node off all
displayentity Set Node on 3
displayentity Set Node off all
displayentity Set Node on 4
displayentity Set Node off all
displayentity Set Node on 5
displayentity Set Node off all
displayentity Set Node on 7
displayentity Set Node off all
displayentity Set Node on 8
displayentity Set Node off all
displayentity Set Node on 10
displayentity Set Node off all
displayentity Set Node on 11
displayentity Set Node off all
displayentity Set Node on 13
displayentity Set Node off all
displayentity Set Node on 14
displayentity Set Node off all
displayentity Set Node on 16
displayentity Set Node off all
displayentity Set Node on 17
displayentity Set Node off all
displayentity Set Node on 16
displayentity Set Node off all
displayentity Set Node on 14
displayentity Set Node off all
displayentity Set Node on 13
displayentity Set Node off all
displayentity Set Node on 11
displayentity Set Node off all
displayentity Set Node on 10
displayentity Set Node off all
displayentity Set Node on 8
displayentity Set Node off all
displayentity Set Node on 7
displayentity Set Node off all
displayentity Set Node on 5
displayentity Set Node off all
displayentity Set Node on 4
displayentity Set Node off all
displayentity Set Node on 3
displayentity Set Node off all
displayentity Set Node on 2
displayentity Set Node off all
displayentity Set Node on 1
pan -17.020311 -11.447202
Save Config. parameters to file C:\Users\Sonic\AppData\Roaming\LSTC\LS-PrePost4.12\lsppconf
