using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using SpaceClaim.Api.V252.MXDigitalTwinModeller.Models.GmshMesher;
using SpaceClaim.Api.V252.MXDigitalTwinModeller.Services.Material;

namespace SpaceClaim.Api.V252.MXDigitalTwinModeller.Services.GmshMesher
{
    /// <summary>
    /// Writes LS-DYNA K-file from Gmsh mesh data.
    /// Coordinates: m → mm (×1000)
    /// </summary>
    // @lat: [[mesh#Gmsh Mesher#.k 파일 변환]]
    public static class GmshKFileWriter
    {
        public static void WriteKFile(string path, GmshMeshData meshData, Part part, List<string> log)
        {
            var sb = new StringBuilder();

            sb.AppendLine("$ LS-DYNA K-file generated by MX Digital Twin Modeller (Gmsh)");
            sb.AppendLine("$");
            sb.AppendLine("*KEYWORD");
            sb.AppendLine("*TITLE");
            sb.AppendLine("Gmsh Mesh Export");
            sb.AppendLine("$");

            // --- *NODE ---
            sb.AppendLine("*NODE");
            sb.AppendLine("$      nid               x               y               z      tc      rc");
            foreach (var kvp in meshData.Nodes)
            {
                var n = kvp.Value;
                // Convert meters to mm
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0,8}{1,16:G10}{2,16:G10}{3,16:G10}       0       0",
                    n.Id, n.X * 1000.0, n.Y * 1000.0, n.Z * 1000.0);
                sb.AppendLine();
            }
            sb.AppendLine("$");

            // --- Per-body parts: one *PART/*SECTION/*MAT per distinct gmsh volume tag ---
            // Gmsh volume tags are 1-based in STEP import order (== part body order, the same
            // assumption body_overrides uses), so tag t maps to part body index t-1. Previously
            // everything collapsed into pid=1 with the FIRST body's material — a physically
            // wrong deck for multi-material assemblies.
            var volumeTags = new List<int>();
            foreach (var elem in meshData.VolumeElements)
                if (!volumeTags.Contains(elem.EntityTag)) volumeTags.Add(elem.EntityTag);
            volumeTags.Sort();
            if (volumeTags.Count == 0) volumeTags.Add(1); // degenerate: keep a valid deck shape

            var tagToPid = new Dictionary<int, int>();
            for (int t = 0; t < volumeTags.Count; t++) tagToPid[volumeTags[t]] = t + 1;

            var partBodies = new List<DesignBody>();
            if (part != null)
            {
                try { foreach (var b in part.Bodies) partBodies.Add(b); } catch { }
            }

            // Per-part ELFORM from that part's own elements (10=Tet4, 1=Hex8, 16=Tet10)
            var pidHasTet10 = new Dictionary<int, bool>();
            var pidHasHex8 = new Dictionary<int, bool>();
            bool hasTet10 = false;
            foreach (var elem in meshData.VolumeElements)
            {
                int p2 = tagToPid[elem.EntityTag];
                if (elem.Type == GmshElementType.Tet10) { pidHasTet10[p2] = true; hasTet10 = true; }
                if (elem.Type == GmshElementType.Hex8) pidHasHex8[p2] = true;
            }

            foreach (var tag in volumeTags)
            {
                int pid2 = tagToPid[tag];
                double density = 7.85e-9;   // tonne/mm³ (steel default)
                double elasticMod = 210000; // MPa
                double poisson = 0.3;
                string partTitle = "GmshPart_" + pid2.ToString(CultureInfo.InvariantCulture);
                int bodyIdx = tag - 1;
                if (bodyIdx >= 0 && bodyIdx < partBodies.Count)
                {
                    try
                    {
                        var body = partBodies[bodyIdx];
                        if (!string.IsNullOrEmpty(body.Name)) partTitle = body.Name;
                        double dens;
                        string matName = MaterialService.ReadBodyMaterialName(body, out dens);
                        if (matName != null)
                        {
                            density = dens;
                            double[] cached = MaterialService.GetCachedValues(matName);
                            if (cached != null && cached.Length >= 3)
                            {
                                density = cached[0];
                                elasticMod = cached[1];
                                poisson = cached[2];
                            }
                        }
                    }
                    catch { }
                }

                int elform = 10;
                if (pidHasHex8.ContainsKey(pid2)) elform = 1;
                if (pidHasTet10.ContainsKey(pid2)) elform = 16;

                sb.AppendLine("*PART");
                sb.AppendLine("$                                                                     title");
                sb.AppendLine(partTitle);
                sb.AppendLine("$      pid     secid       mid     eosid      hgid      grav    adpopt      tmid");
                sb.AppendFormat("{0,10}{1,10}{2,10}         0         0         0         0         0",
                    pid2, pid2, pid2);
                sb.AppendLine();
                sb.AppendLine("$");

                sb.AppendLine("*SECTION_SOLID");
                sb.AppendLine("$    secid    elform       aet");
                sb.AppendFormat("{0,10}{1,10}         0", pid2, elform);
                sb.AppendLine();
                sb.AppendLine("$");

                sb.AppendLine("*MAT_ELASTIC");
                sb.AppendLine("$      mid        ro         e        pr        da        db  not used");
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0,10}{1,10:G6}{2,10:G6}{3,10:G6}          0.0          0.0          0.0",
                    pid2, density, elasticMod, poisson);
                sb.AppendLine();
                sb.AppendLine("$");
            }

            // --- *ELEMENT_SOLID ---
            if (meshData.VolumeElements.Count > 0)
            {
                bool useLongFormat = hasTet10;

                if (useLongFormat)
                    sb.AppendLine("*ELEMENT_SOLID_LONG");
                else
                    sb.AppendLine("*ELEMENT_SOLID");

                sb.AppendLine("$      eid     pid      n1      n2      n3      n4      n5      n6      n7      n8");

                foreach (var elem in meshData.VolumeElements)
                {
                    int epid = tagToPid[elem.EntityTag];
                    if (elem.Type == GmshElementType.Tet4)
                    {
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, epid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            0, 0, 0, 0);
                        sb.AppendLine();
                    }
                    else if (elem.Type == GmshElementType.Hex8)
                    {
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, epid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            elem.NodeIds[4], elem.NodeIds[5], elem.NodeIds[6], elem.NodeIds[7]);
                        sb.AppendLine();
                    }
                    else if (elem.Type == GmshElementType.Tet10)
                    {
                        // Long format: 10 nodes
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, epid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            elem.NodeIds[4], elem.NodeIds[5], elem.NodeIds[6], elem.NodeIds[7]);
                        sb.AppendLine();
                        // Continuation line for nodes 9-10
                        sb.AppendFormat("{0,8}{1,8}",
                            elem.NodeIds[8], elem.NodeIds[9]);
                        sb.AppendLine();
                    }
                }
                sb.AppendLine("$");
            }

            // --- *ELEMENT_SHELL (surface triangles) ---
            if (meshData.SurfaceElements.Count > 0)
            {
                sb.AppendLine("*ELEMENT_SHELL");
                sb.AppendLine("$      eid     pid      n1      n2      n3      n4");
                int shellPid = volumeTags.Count + 1;

                foreach (var elem in meshData.SurfaceElements)
                {
                    if (elem.Type == GmshElementType.Tri3)
                    {
                        // n4 = n3 (duplicate for 3-node triangle)
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}",
                            elem.Id, shellPid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[2]);
                        sb.AppendLine();
                    }
                }
                sb.AppendLine("$");
            }

            sb.AppendLine("*END");

            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));

            if (log != null)
                log.Add(string.Format("[KFileWriter] K-file 생성 완료: {0} (노드: {1}, 요소: {2})",
                    path, meshData.TotalNodeCount, meshData.TotalElementCount));
        }
    }
}
