using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using SpaceClaim.Api.V252.MXDigitalTwinModeller.Models.GmshMesher;
using SpaceClaim.Api.V252.MXDigitalTwinModeller.Services.Material;

namespace SpaceClaim.Api.V252.MXDigitalTwinModeller.Services.GmshMesher
{
    /// <summary>
    /// Writes LS-DYNA K-file from Gmsh mesh data.
    /// Coordinates: m → mm (×1000)
    /// </summary>
    // @lat: [[mesh#Gmsh Mesher#.k 파일 변환]]
    public static class GmshKFileWriter
    {
        public static void WriteKFile(string path, GmshMeshData meshData, Part part, List<string> log)
        {
            var sb = new StringBuilder();

            sb.AppendLine("$ LS-DYNA K-file generated by MX Digital Twin Modeller (Gmsh)");
            sb.AppendLine("$");
            sb.AppendLine("*KEYWORD");
            sb.AppendLine("*TITLE");
            sb.AppendLine("Gmsh Mesh Export");
            sb.AppendLine("$");

            // --- *NODE ---
            sb.AppendLine("*NODE");
            sb.AppendLine("$      nid               x               y               z      tc      rc");
            foreach (var kvp in meshData.Nodes)
            {
                var n = kvp.Value;
                // Convert meters to mm
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{0,8}{1,16:G10}{2,16:G10}{3,16:G10}       0       0",
                    n.Id, n.X * 1000.0, n.Y * 1000.0, n.Z * 1000.0);
                sb.AppendLine();
            }
            sb.AppendLine("$");

            // --- Determine part/material from SpaceClaim bodies ---
            int pid = 1;
            int secId = 1;
            int mid = 1;
            double density = 7.85e-9;  // tonne/mm³ (steel default)
            double elasticMod = 210000; // MPa
            double poisson = 0.3;

            // Try to get material from first body
            if (part != null)
            {
                try
                {
                    foreach (var body in part.Bodies)
                    {
                        double dens;
                        string matName = MaterialService.ReadBodyMaterialName(body, out dens);
                        if (matName != null)
                        {
                            density = dens;
                            double[] cached = MaterialService.GetCachedValues(matName);
                            if (cached != null && cached.Length >= 3)
                            {
                                density = cached[0];
                                elasticMod = cached[1];
                                poisson = cached[2];
                            }
                            break;
                        }
                    }
                }
                catch { }
            }

            // Determine ELFORM based on element types present
            int elformSolid = 10; // Tet4 default
            bool hasTet10 = false;
            bool hasHex8 = false;

            foreach (var elem in meshData.VolumeElements)
            {
                if (elem.Type == GmshElementType.Tet10) hasTet10 = true;
                if (elem.Type == GmshElementType.Hex8) hasHex8 = true;
            }

            if (hasHex8) elformSolid = 1;
            if (hasTet10) elformSolid = 16;

            // --- *PART ---
            sb.AppendLine("*PART");
            sb.AppendLine("$                                                                     title");
            sb.AppendLine("GmshPart");
            sb.AppendLine("$      pid     secid       mid     eosid      hgid      grav    adpopt      tmid");
            sb.AppendFormat("{0,10}{1,10}{2,10}         0         0         0         0         0",
                pid, secId, mid);
            sb.AppendLine();
            sb.AppendLine("$");

            // --- *SECTION_SOLID ---
            sb.AppendLine("*SECTION_SOLID");
            sb.AppendLine("$    secid    elform       aet");
            sb.AppendFormat("{0,10}{1,10}         0", secId, elformSolid);
            sb.AppendLine();
            sb.AppendLine("$");

            // --- *MAT_ELASTIC ---
            sb.AppendLine("*MAT_ELASTIC");
            sb.AppendLine("$      mid        ro         e        pr        da        db  not used");
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "{0,10}{1,10:G6}{2,10:G6}{3,10:G6}          0.0          0.0          0.0",
                mid, density, elasticMod, poisson);
            sb.AppendLine();
            sb.AppendLine("$");

            // --- *ELEMENT_SOLID ---
            if (meshData.VolumeElements.Count > 0)
            {
                bool useLongFormat = hasTet10;

                if (useLongFormat)
                    sb.AppendLine("*ELEMENT_SOLID_LONG");
                else
                    sb.AppendLine("*ELEMENT_SOLID");

                sb.AppendLine("$      eid     pid      n1      n2      n3      n4      n5      n6      n7      n8");

                foreach (var elem in meshData.VolumeElements)
                {
                    if (elem.Type == GmshElementType.Tet4)
                    {
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, pid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            0, 0, 0, 0);
                        sb.AppendLine();
                    }
                    else if (elem.Type == GmshElementType.Hex8)
                    {
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, pid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            elem.NodeIds[4], elem.NodeIds[5], elem.NodeIds[6], elem.NodeIds[7]);
                        sb.AppendLine();
                    }
                    else if (elem.Type == GmshElementType.Tet10)
                    {
                        // Long format: 10 nodes
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}{6,8}{7,8}{8,8}{9,8}",
                            elem.Id, pid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[3],
                            elem.NodeIds[4], elem.NodeIds[5], elem.NodeIds[6], elem.NodeIds[7]);
                        sb.AppendLine();
                        // Continuation line for nodes 9-10
                        sb.AppendFormat("{0,8}{1,8}",
                            elem.NodeIds[8], elem.NodeIds[9]);
                        sb.AppendLine();
                    }
                }
                sb.AppendLine("$");
            }

            // --- *ELEMENT_SHELL (surface triangles) ---
            if (meshData.SurfaceElements.Count > 0)
            {
                sb.AppendLine("*ELEMENT_SHELL");
                sb.AppendLine("$      eid     pid      n1      n2      n3      n4");
                int shellPid = pid + 1;

                foreach (var elem in meshData.SurfaceElements)
                {
                    if (elem.Type == GmshElementType.Tri3)
                    {
                        // n4 = n3 (duplicate for 3-node triangle)
                        sb.AppendFormat("{0,8}{1,8}{2,8}{3,8}{4,8}{5,8}",
                            elem.Id, shellPid,
                            elem.NodeIds[0], elem.NodeIds[1], elem.NodeIds[2], elem.NodeIds[2]);
                        sb.AppendLine();
                    }
                }
                sb.AppendLine("$");
            }

            sb.AppendLine("*END");

            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));

            if (log != null)
                log.Add(string.Format("[KFileWriter] K-file 생성 완료: {0} (노드: {1}, 요소: {2})",
                    path, meshData.TotalNodeCount, meshData.TotalElementCount));
        }
    }
}
