using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using SpaceClaim.Api.V252.MXDigitalTwinModeller.Models.GmshMesher;

namespace SpaceClaim.Api.V252.MXDigitalTwinModeller.Services.GmshMesher
{
    // @lat: [[mesh#Gmsh Mesher#.geo 라이터]]
    public static class GmshGeoWriter
    {
        /// <summary>
        /// Generate a .geo script for Gmsh from a STEP file and mesh parameters.
        /// Element sizes in parameters are in mm; they are converted to meters for Gmsh (STEP uses meters).
        /// </summary>
        public static void WriteGeoFile(string geoPath, string stepPath, GmshMeshParameters p, List<string> log)
        {
            double globalSizeM = p.GlobalElementSizeMm / 1000.0;
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by MX Digital Twin Modeller");
            sb.AppendLine("SetFactory(\"OpenCASCADE\");");
            sb.AppendLine();

            // Merge STEP file
            string escapedStep = stepPath.Replace("\\", "/");
            sb.AppendFormat(CultureInfo.InvariantCulture, "Merge \"{0}\";", escapedStep);
            sb.AppendLine();
            sb.AppendLine();

            // Global mesh settings
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "Mesh.CharacteristicLengthMin = {0:G6};", globalSizeM * 0.1);
            sb.AppendLine();
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "Mesh.CharacteristicLengthMax = {0:G6};", globalSizeM * 5.0);
            sb.AppendLine();
            sb.AppendLine();

            // Element order
            sb.AppendFormat("Mesh.ElementOrder = {0};", p.MidsideNodes ? 2 : 1);
            sb.AppendLine();

            // Algorithm
            if (p.Algorithm != MeshAlgorithm.Auto)
            {
                sb.AppendFormat("Mesh.Algorithm3D = {0};", (int)p.Algorithm);
                sb.AppendLine();
            }

            // Growth rate
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "Mesh.CharacteristicLengthExtendFromBoundary = 1;");
            sb.AppendLine();

            // Hex meshing (Recombine)
            if (p.Shape == ElementShape.Hex)
            {
                sb.AppendLine("Mesh.RecombineAll = 1;");
                sb.AppendLine("Mesh.Recombine3DAll = 1;");
                sb.AppendLine("Mesh.Algorithm3D = 10; // HXT for hex");
            }

            sb.AppendLine();

            // Size fields for body overrides
            int fieldId = 1;
            var fieldIds = new List<int>();

            foreach (var ovr in p.BodyOverrides)
            {
                double ovrSizeM = ovr.ElementSizeMm / 1000.0;
                int mathFieldId = fieldId++;
                int restrictFieldId = fieldId++;

                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}] = MathEval;", mathFieldId);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].F = \"{1:G6}\";", mathFieldId, ovrSizeM);
                sb.AppendLine();

                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}] = Restrict;", restrictFieldId);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].InField = {1};", restrictFieldId, mathFieldId);
                sb.AppendLine();
                // Volume index in Gmsh is 1-based from STEP import order
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].RegionsList = {{{1}}};", restrictFieldId, ovr.BodyIndex + 1);
                sb.AppendLine();
                sb.AppendLine();

                fieldIds.Add(restrictFieldId);
            }

            // Background field as global size
            int bgFieldId = fieldId++;
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "Field[{0}] = MathEval;", bgFieldId);
            sb.AppendLine();
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "Field[{0}].F = \"{1:G6}\";", bgFieldId, globalSizeM);
            sb.AppendLine();
            fieldIds.Add(bgFieldId);

            // Min field to combine all
            if (fieldIds.Count > 0)
            {
                int minFieldId = fieldId++;
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}] = Min;", minFieldId);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].FieldsList = {{{1}}};", minFieldId, string.Join(",", fieldIds));
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Background Field = {0};", minFieldId);
                sb.AppendLine();
                sb.AppendLine("Mesh.MeshSizeExtendFromBoundary = 0;");
                sb.AppendLine("Mesh.MeshSizeFromPoints = 0;");
                sb.AppendLine("Mesh.MeshSizeFromCurvature = 0;");
            }

            sb.AppendLine();

            // Refinement box (future)
            if (p.UseRefinementBox)
            {
                int boxFieldId = fieldId++;
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}] = Box;", boxFieldId);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].VIn = {1:G6};", boxFieldId, p.RefinementBoxSizeMm / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].VOut = {1:G6};", boxFieldId, globalSizeM);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].XMin = {1:G6};", boxFieldId, p.RefinementBoxXMin / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].XMax = {1:G6};", boxFieldId, p.RefinementBoxXMax / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].YMin = {1:G6};", boxFieldId, p.RefinementBoxYMin / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].YMax = {1:G6};", boxFieldId, p.RefinementBoxYMax / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].ZMin = {1:G6};", boxFieldId, p.RefinementBoxZMin / 1000.0);
                sb.AppendLine();
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "Field[{0}].ZMax = {1:G6};", boxFieldId, p.RefinementBoxZMax / 1000.0);
                sb.AppendLine();
                sb.AppendLine();
            }

            File.WriteAllText(geoPath, sb.ToString(), new UTF8Encoding(false));

            if (log != null)
                log.Add(string.Format("[GeoWriter] .geo 파일 생성 완료: {0}", geoPath));
        }
    }
}
